// MAPS_SCREEN ACTION TYPES
export const MAPS_SCREEN_SEARCH_SUCCESS = 'MAPS_SCREEN_SEARCH_SUCCESS';
export const MAPS_SCREEN_SEARCH_ERROR = 'MAPS_SCREEN_SERACH_ERROR';
export const MAPS_SCREEN_SEARCH_LOADING = 'MAPS_SCREEN_SEARCH_LOADING';
export const MAPS_SCREEN_UPDATE_MY_CURRENT_LOCATION = 'MAPS_SCREEN_UPDATE_MY_CURRENT_LOCATION';
export const MAPS_SCREEN_UPDATE_PICK_UP_POINT = 'MAPS_SCREEN_UPDATE_PICK_UP_POINT';
export const MAPS_SCREEN_UPDATE_DROP_OFF_POINT = 'MAPS_SCREEN_UPDATE_DROP_OFF_POINT';
export const MAPS_SCREEN_UPDATE_MY_CURRENT_LOCATION_AND_CURRENT_REGION = 'MAPS_SCREEN_UPDATE_MY_CURRENT_LOCATION_AND_CURRENT_REGION';
export const MAPS_SCREEN_SEARCH_STRING_UPDATE = 'MAPS_SCREEN_SEARCH_STRING_UPDATE';
export const MAPS_SCREEN_CURRENT_REGION_UPDATE = 'MAPS_SCREEN_CURRENT_REGION_UPDATE';
export const MAP_SCREEN_GET_ROUTE = 'MAP_SCREEN_GET_ROUTE';
export const MAP_SCREEN_GET_ROUTE_SUCCESS = 'MAP_SCREEN_GET_ROUTE_SUCCESS';
export const MAP_SCREEN_GET_ROUTE_ERROR = 'MAP_SCREEN_GET_ROUTE_ERROR';
